// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    title: "E-Commerce Store",
    parag: `E-Commerce Store project, It was a great and complex project but i faced a lot of problems one of them that in the payment stage that when the payment is done the cart still has the items so i made a function to empty the cart.`,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKLUQhg-bldzlqSxd24wIo2mP4Zb5l6XFYew&usqp=CAU",
    demo: "https://elaidy-e-commerce-app.netlify.app/",
    github: "https://github.com/AhmedElaidy/The-E-Commerce-App",
    type: "React",
    color: "blue",
  },
  {
    id: 2,
    title: "Movies App",
    parag: `Movies-App project is a react project that has a lot of functions, it also has a lot of pages that made with react router, it also has a page for every movie that have a lot of details about the film such as it's itme, quality, release date and description.`,
    img: "https://codecanyon.img.customer.envatousercontent.com/files/398200153/07_Streamit-app.jpg?auto=compress%2Cformat&fit=crop&crop=top&w=590&h=300&s=3cc97c85bd37f6857f83f47a9bf794bb",
    demo: "https://elaidy-movies.netlify.app/",
    github: "https://github.com/AhmedElaidy/Movies-Project",
    type: "React",
    color: "blue",
  },
  {
    id: 3,
    title: "Portfolio",
    parag: `Portfolio project is a great react project that I used a lot of ideas in it, one of these ideas was to put all the data in an external file and make a loop over them and show all of them throw one component which make project faster.`,
    img: "https://i.ibb.co/Kzvg0tp/Screenshot-2023-10-30-233446.png",
    demo: "https://elaidy-portfolio.netlify.app/",
    github: "https://github.com/AhmedElaidy/Portfolio-Project",
    type: "React",
    color: "blue",
  },
  {
    id: 4,
    title: "Cocktailes",
    parag: `Cocktail is a React project that has a lot of drinks,Cocktail has 2 pages, one is 'home' that is for drinks and another one is 'About'.`,
    img: "https://i.ibb.co/sKT8Yp5/Screenshot-2023-10-30-233626.png",
    demo: "https://elaidy-cocktail.netlify.app/",
    github: "https://github.com/AhmedElaidy/Cocktails-Project",
    type: "React",
    color: "blue",
  },
  {
    id: 5,
    title: "The Menu",
    parag: `The Menu is a JavaScript project whose function is to show you the types of food based on your choice, I also used a function that makes a loop over the whole list of food and only shows the food that kind matches the food kind you chose. `,
    img: "https://i.ibb.co/WBKz2Ny/Screenshot-2023-10-30-233932.png",
    demo: "https://ahmedelaidy.github.io/The-Menu-Project/",
    github: "https://github.com/AhmedElaidy/The-Menu-Project",
    type: "JavaScript",
    color: "yellow",
  },
  {
    id: 6,
    title: "Calculator",
    parag: `The Calculator is a calculator with a them button, it takes the values you give to it and gives you the result back, when you click the theme button it switches between calculator themes. `,
    img: "https://res.cloudinary.com/dz209s6jk/image/upload/v1652199545/Challenges/xye51b9no1nkpuonov8r.jpg",
    demo: "https://ahmedelaidy.github.io/The-Calculator/",
    github: "https://github.com/AhmedElaidy/The-Calculator",
    type: "JavaScript",
    color: "yellow",
  },
  {
    id: 7,
    title: "Scroll",
    parag: `Scroll is a JavaScript project that has navbar and a lot of sections, When any button in the navbar is been clicked it takes you to the section that matches the name of the button you clicked and also there is scroll to top button.`,
    img: "https://i.ibb.co/TtQCVsP/Screenshot-2023-10-30-233833.png",
    demo: "https://ahmedelaidy.github.io/Scroll-Project/",
    github: "https://github.com/AhmedElaidy/Scroll-Project",
    type: "JavaScript",
    color: "yellow",
  },
  {
    id: 8,
    title: "Video",
    parag: `The Video is a JavaScript project that has 2 buttons, Preloader video that when the page is loading and disappear after that and there is a button that run a funtion that run or stop the video when it clicked.`,
    img: "https://i.ibb.co/f2NsTZQ/Screenshot-2023-10-30-234244.png",
    demo: "https://ahmedelaidy.github.io/The-Video-Project/",
    github: "https://github.com/AhmedElaidy/The-Video-Project",
    type: "JavaScript",
    color: "yellow",
  },
];
